-- Roles
CREATE ROLE :"POSTGRES_RW_USER" LOGIN PASSWORD :'POSTGRES_RW_PASSWORD';
CREATE ROLE :"POSTGRES_RO_USER" LOGIN PASSWORD :'POSTGRES_RO_PASSWORD';

-- Connexion DB
GRANT CONNECT ON DATABASE :"POSTGRES_DB" TO :"POSTGRES_RW_USER", :"POSTGRES_RO_USER";

-- Schema
GRANT USAGE ON SCHEMA :"POSTGRES_SCHEMA" TO :"POSTGRES_RW_USER", :"POSTGRES_RO_USER";

-- Tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA :"POSTGRES_SCHEMA" TO :"POSTGRES_RW_USER";
GRANT SELECT ON ALL TABLES IN SCHEMA :"POSTGRES_SCHEMA" TO :"POSTGRES_RO_USER";

-- Séquences (si colonnes SERIAL/IDENTITY)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA :"POSTGRES_SCHEMA" TO :"POSTGRES_RW_USER";

-- Types
GRANT USAGE ON TYPE :"POSTGRES_SCHEMA".role_enum TO :"POSTGRES_RW_USER", :"POSTGRES_RO_USER";
GRANT USAGE ON TYPE :"POSTGRES_SCHEMA".game_status_enum TO :"POSTGRES_RW_USER", :"POSTGRES_RO_USER";
GRANT USAGE ON TYPE :"POSTGRES_SCHEMA".period_enum TO :"POSTGRES_RW_USER", :"POSTGRES_RO_USER";
GRANT USAGE ON TYPE :"POSTGRES_SCHEMA".action_type_enum TO :"POSTGRES_RW_USER", :"POSTGRES_RO_USER";

-- Pour que les futures tables aient automatiquement les bons droits
ALTER DEFAULT PRIVILEGES IN SCHEMA :"POSTGRES_SCHEMA"
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"POSTGRES_RW_USER";

ALTER DEFAULT PRIVILEGES IN SCHEMA :"POSTGRES_SCHEMA"
GRANT SELECT ON TABLES TO :"POSTGRES_RO_USER";

ALTER DEFAULT PRIVILEGES IN SCHEMA :"POSTGRES_SCHEMA"
GRANT USAGE, SELECT ON SEQUENCES TO :"POSTGRES_RW_USER";